# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tmux-version: [3.0a]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ca-certificates fontconfig git gcc iputils-ping libevent-dev libncurses-dev locales make procps wget

      # Runs a set of commands using the runners shell
      - name: Compile tmux version ${{ matrix.tmux-version }}
        run: |
          cd ~
          VERSION=${{ matrix.tmux-version }}
          wget -O - https://github.com/tmux/tmux/releases/download/$VERSION/tmux-$VERSION.tar.gz | tar xzf -
          cd tmux-$VERSION
          LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" ./configure --prefix=/usr/local
          make
          make install
          cd ..
          rm -rf tmux-$VERSION
      - name: Install tmux-config
        run: |
          cd ~
          git clone https://github.com/joserconde/tmux-config.git \
          ./tmux-config/install.sh
          rm -rf ./tmux-config
